# Generated by Django 2.1 on 2018-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0002_auto_20180915_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='Absent_on',
            field=models.ManyToManyField(blank=True, to='Admissions.Absent_date'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='Gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='MALE', max_length=10),
        ),
    ]
