# Generated by Django 2.1 on 2018-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0004_auto_20180921_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='Absent_on',
            field=models.ManyToManyField(blank=True, to='Admissions.Absent_date'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='Gender',
            field=models.CharField(choices=[('others', 'OTHERS'), ('female', 'FEMALE'), ('male', 'MALE')], default='MALE', max_length=10),
        ),
    ]
