# Generated by Django 2.1 on 2018-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0007_auto_20180923_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholar',
            name='Test1',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test10',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test2',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test3',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test4',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test5',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test6',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test7',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test8',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Test9',
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test10_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject1',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject10',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject2',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject3',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject5',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject6',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject7',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject8',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_subject9',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.DeleteModel(
            name='Test10',
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
        migrations.DeleteModel(
            name='Test3',
        ),
        migrations.DeleteModel(
            name='Test4',
        ),
        migrations.DeleteModel(
            name='Test5',
        ),
        migrations.DeleteModel(
            name='Test6',
        ),
        migrations.DeleteModel(
            name='Test7',
        ),
        migrations.DeleteModel(
            name='Test8',
        ),
        migrations.DeleteModel(
            name='Test9',
        ),
    ]
