# Generated by Django 2.1 on 2018-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissions', '0008_auto_20180924_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='Test10_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test1_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test2_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test3_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test4_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test5_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test6_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test7_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test8_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='scholar',
            name='Test9_Rank',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='Gender',
            field=models.CharField(choices=[('female', 'FEMALE'), ('others', 'OTHERS'), ('male', 'MALE')], default='MALE', max_length=10),
        ),
    ]
