# Generated by Django 2.1 on 2018-09-15 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(default='1:A', help_text='example :LKG:A UKG:A 1:A 1:B 2:A 2:B......12:A 12:B 12:C 12:D ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('Class', models.CharField(choices=[('pre k.g', 'PRE KG'), ('l.k.g', 'LKG'), ('u.k.g', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('General', 'GENERAL')], max_length=10)),
                ('description', models.CharField(max_length=5000)),
                ('Document_type', models.CharField(choices=[('others', 'OTHERS'), ('Book', 'BOOK'), ('Notes', 'NOTES'), ('Magazines', 'MAGAZINES'), ('question_paper', 'Question Paper')], max_length=25)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Test_and_exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='Subject',
            field=models.ManyToManyField(to='staffs.subject'),
        ),
        migrations.AddField(
            model_name='staff',
            name='classes',
            field=models.ManyToManyField(to='staffs.classdivision'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete='CASCADE', to='staffs.subject'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_by',
            field=models.ForeignKey(on_delete='CASCADE', related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classdivision',
            name='Subject',
            field=models.ManyToManyField(to='staffs.subject'),
        ),
        migrations.AddField(
            model_name='classdivision',
            name='Tests',
            field=models.ManyToManyField(blank=True, to='staffs.Test_and_exam'),
        ),
    ]
