# Generated by Django 2.1 on 2018-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Magazines', 'MAGAZINES'), ('Notes', 'NOTES'), ('question_paper', 'Question Paper'), ('others', 'OTHERS'), ('Book', 'BOOK')], max_length=25),
        ),
    ]
