# Generated by Django 2.1 on 2018-09-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20180915_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Book', 'BOOK'), ('Notes', 'NOTES'), ('question_paper', 'Question Paper'), ('Magazines', 'MAGAZINES'), ('others', 'OTHERS')], max_length=25),
        ),
    ]
