# Generated by Django 2.1 on 2018-09-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20180915_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('question_paper', 'Question Paper'), ('Magazines', 'MAGAZINES'), ('Notes', 'NOTES'), ('Book', 'BOOK'), ('others', 'OTHERS')], max_length=25),
        ),
    ]
