# Generated by Django 2.1 on 2018-09-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_auto_20180921_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Notes', 'NOTES'), ('Book', 'BOOK'), ('others', 'OTHERS'), ('question_paper', 'Question Paper'), ('Magazines', 'MAGAZINES')], max_length=25),
        ),
    ]
