# Generated by Django 2.1 on 2018-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20180921_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Book', 'BOOK'), ('question_paper', 'Question Paper'), ('others', 'OTHERS'), ('Notes', 'NOTES'), ('Magazines', 'MAGAZINES')], max_length=25),
        ),
    ]
