# Generated by Django 2.1 on 2018-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_auto_20180923_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Notes', 'NOTES'), ('Book', 'BOOK'), ('others', 'OTHERS'), ('Magazines', 'MAGAZINES'), ('question_paper', 'Question Paper')], max_length=25),
        ),
    ]
