# Generated by Django 2.1 on 2018-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0007_auto_20180923_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Notes', 'NOTES'), ('others', 'OTHERS'), ('question_paper', 'Question Paper'), ('Magazines', 'MAGAZINES'), ('Book', 'BOOK')], max_length=25),
        ),
    ]
