# Generated by Django 2.1 on 2018-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_auto_20180924_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_type',
            field=models.CharField(choices=[('Book', 'BOOK'), ('question_paper', 'Question Paper'), ('Notes', 'NOTES'), ('Magazines', 'MAGAZINES'), ('others', 'OTHERS')], max_length=25),
        ),
    ]
